# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Simulation.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.LeftPanel = QtWidgets.QWidget(self.centralwidget)
        self.LeftPanel.setGeometry(QtCore.QRect(130, 10, 351, 461))
        self.LeftPanel.setObjectName("LeftPanel")
        self.widget = QtWidgets.QWidget(self.LeftPanel)
        self.widget.setGeometry(QtCore.QRect(30, 70, 507, 241))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.ScenarioType = QtWidgets.QGroupBox(self.widget)
        self.ScenarioType.setObjectName("ScenarioType")
        self.horizontalLayout.addWidget(self.ScenarioType)
        self.Parameters = QtWidgets.QGroupBox(self.widget)
        self.Parameters.setObjectName("Parameters")
        self.horizontalLayout.addWidget(self.Parameters)
        self.Reset = QtWidgets.QPushButton(self.widget)
        self.Reset.setObjectName("Reset")
        self.horizontalLayout.addWidget(self.Reset)
        self.Simulation = QtWidgets.QGroupBox(self.widget)
        self.Simulation.setObjectName("Simulation")
        self.horizontalLayout.addWidget(self.Simulation)
        self.pushButton_2 = QtWidgets.QPushButton(self.widget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.RightPanel = QtWidgets.QWidget(self.centralwidget)
        self.RightPanel.setGeometry(QtCore.QRect(450, 30, 28, 18))
        self.RightPanel.setObjectName("RightPanel")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.RightPanel)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.widget1 = QtWidgets.QWidget(self.RightPanel)
        self.widget1.setObjectName("widget1")
        self.horizontalLayout_2.addWidget(self.widget1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.ScenarioType.setTitle(_translate("MainWindow", "GroupBox"))
        self.Parameters.setTitle(_translate("MainWindow", "GroupBox"))
        self.Reset.setText(_translate("MainWindow", "PushButton"))
        self.Simulation.setTitle(_translate("MainWindow", "GroupBox"))
        self.pushButton_2.setText(_translate("MainWindow", "PushButton"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
